// <auto-generated />
namespace TallerDeMotos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CreacionDeTablaPersonerias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreacionDeTablaPersonerias));
        
        string IMigrationMetadata.Id
        {
            get { return "201709211933126_CreacionDeTablaPersonerias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
